commonAnnotations:
  argocd.argoproj.io/sync-options: Replace=true
resources:
- ./0namespace-namespace.yaml
- ./prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
- ./prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- ./prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- ./prometheus-operator-0probeCustomResourceDefinition.yaml
- ./prometheus-operator-0prometheusagentCustomResourceDefinition.yaml
- ./prometheus-operator-0prometheusCustomResourceDefinition.yaml
- ./prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- ./prometheus-operator-0scrapeconfigCustomResourceDefinition.yaml
- ./prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- ./prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- ./prometheus-operator-clusterRoleBinding.yaml
- ./prometheus-operator-clusterRole.yaml
- ./prometheus-operator-deployment.yaml
- ./prometheus-operator-networkPolicy.yaml
- ./prometheus-operator-serviceAccount.yaml
- ./prometheus-operator-service.yaml
